FORMAT: 1A
HOST: http://localhost:3000/

# WBooks API

Welcome to the WBook API! In this documentation you will find all the necessary information to be able to use the API resources.

## User Sessions [/auth/sign_in]

### Create [POST]

The API uses [Devise Token Auth](https://github.com/lynndylanhurley/devise_token_auth), which will receive an email and a password,
if the info provided is correctly verified, it will respond with the data of the logged user and headers for access-token, client and uid, that must be used later in the
header of requests that require user authentification.

+ Request (application/json)

        {
            "email": "test@wolox.com.ar",
            "password": "123123123"
        }

+ Response 200 (application/json)

    + Headers

            access-token: DyVgA1zQCrq38--fWQ8mLg
            token-type: Bearer
            client: gNF8jGwgA4-uIfqGoxGo2Q
            expiry: 1554911514
            uid: test@wolox.com.ar
            ETag: W/"acc923a414a0811d7efa7cedc6ac3d73"
            Cache-Control: max-age=0, private, must-revalidate
            X-Request-Id: 704e7aed-5a9e-49e0-9d4d-8fc1eac264d2
            X-Runtime: 0.420566
            Transfer-Encoding: chunked
            
    + Body

            {
                "data": {
                    "id": 1,
                    "email": "test@wolox.com.ar",
                    "provider": "email",
                    "uid": "test@wolox.com.ar",
                    "allow_password_change": false,
                    "first_name": "Test",
                    "last_name": "TestLastName",
                    "locale": "en"
                }
            }

## Books List [/api/v1/books]

### Index [GET]

Lists all the books and their information, note that the response is paginated and each page has 25 records.
Pagination is done through [wor-paginate](https://github.com/Wolox/wor-paginate)

+ Request (application/json)

    + Headers

            access-token: DyVgA1zQCrq38--fWQ8mLg
            client: gNF8jGwgA4-uIfqGoxGo2Q
            uid: test@wolox.com.ar

+ Response 200 (application/json)

            
    + Body

            {
                "page": [
                    {
                        "id": 57794,
                        "author": "Rufus Bartoletti",
                        "title": "Dying of the Light",
                        "image": "http://bartolettihyatt.io/kasi",
                        "editor": "Flame Tree Publishing",
                        "year": "1962",
                        "genre": "Short story",
                        "created_at": "2019-03-19T14:59:38.835Z",
                        "updated_at": "2019-03-19T14:59:38.835Z",
                        "rents": []
                    },
                    {
                        "id": 57795,
                        "author": "Randee Bode",
                        "title": "The Moving Toyshop",
                        "image": "http://roob.biz/fletcher_parisian",
                        "editor": "Borgo Press",
                        "year": "1945",
                        "genre": "Historical fiction",
                        "created_at": "2019-03-19T14:59:38.841Z",
                        "updated_at": "2019-03-19T14:59:38.841Z",
                        "rents": []
                    },
                    {
                        "id": 57796,
                        "author": "Dr. Samual Hayes",
                        "title": "An Instant In The Wind",
                        "image": "http://borer.name/cyndi.kunde",
                        "editor": "Mark Batty Publisher",
                        "year": "1991",
                        "genre": "Fiction narrative",
                        "created_at": "2019-03-19T14:59:38.843Z",
                        "updated_at": "2019-03-19T14:59:38.843Z",
                        "rents": []
                    },
                    {
                        "id": 57797,
                        "author": "Jared O'Reilly",
                        "title": "The Green Bay Tree",
                        "image": "http://green.info/harlan.feeney",
                        "editor": "Open Court Publishing Company",
                        "year": "2003",
                        "genre": "Short story",
                        "created_at": "2019-03-19T14:59:38.845Z",
                        "updated_at": "2019-03-19T14:59:38.845Z",
                        "rents": []
                    },
                    {
                        "id": 57798,
                        "author": "Daren Harvey",
                        "title": "Nine Coaches Waiting",
                        "image": "http://connellyko.com/rosaria",
                        "editor": "Manchester University Press",
                        "year": "1998",
                        "genre": "Fiction narrative",
                        "created_at": "2019-03-19T14:59:38.847Z",
                        "updated_at": "2019-03-19T14:59:38.847Z",
                        "rents": []
                    },
                    {
                        "id": 57799,
                        "author": "Catarina Donnelly",
                        "title": "The Lathe of Heaven",
                        "image": "http://ornklein.co/candice",
                        "editor": "Lethe Press",
                        "year": "1996",
                        "genre": "Fable",
                        "created_at": "2019-03-19T14:59:38.849Z",
                        "updated_at": "2019-03-19T14:59:38.849Z",
                        "rents": []
                    },
                    {
                        "id": 57800,
                        "author": "Mr. Junie Runte",
                        "title": "An Evil Cradling",
                        "image": "http://buckridge.net/huong",
                        "editor": "Macmillan Publishers",
                        "year": "2008",
                        "genre": "Legend",
                        "created_at": "2019-03-19T14:59:38.852Z",
                        "updated_at": "2019-03-19T14:59:38.852Z",
                        "rents": []
                    },
                    {
                        "id": 57801,
                        "author": "Darren Turner PhD",
                        "title": "I Sing the Body Electric",
                        "image": "http://walkerconn.net/margarito.welch",
                        "editor": "ECW Press",
                        "year": "1961",
                        "genre": "Narrative nonfiction",
                        "created_at": "2019-03-19T14:59:38.854Z",
                        "updated_at": "2019-03-19T14:59:38.854Z",
                        "rents": []
                    },
                    {
                        "id": 57802,
                        "author": "Robt Will",
                        "title": "The Torment of Others",
                        "image": "http://parisian.name/donnie.purdy",
                        "editor": "Marshall Cavendish",
                        "year": "1955",
                        "genre": "Fiction in verse",
                        "created_at": "2019-03-19T14:59:38.856Z",
                        "updated_at": "2019-03-19T14:59:38.856Z",
                        "rents": []
                    },
                    {
                        "id": 57803,
                        "author": "Alda Kassulke",
                        "title": "Time of our Darkness",
                        "image": "http://ondricka.com/percy",
                        "editor": "Fairview Press",
                        "year": "1957",
                        "genre": "Essay",
                        "created_at": "2019-03-19T14:59:38.858Z",
                        "updated_at": "2019-03-19T14:59:38.858Z",
                        "rents": []
                    },
                    {
                        "id": 57804,
                        "author": "Mia Ruecker I",
                        "title": "A Summer Bird-Cage",
                        "image": "http://ullrichgulgowski.net/vena.fay",
                        "editor": "Cambridge University Press",
                        "year": "2018",
                        "genre": "Fiction narrative",
                        "created_at": "2019-03-19T14:59:38.861Z",
                        "updated_at": "2019-03-19T14:59:38.861Z",
                        "rents": []
                    },
                    {
                        "id": 57807,
                        "author": "Ismael Kertzmann",
                        "title": "The Golden Bowl",
                        "image": "http://aufderhar.co/fae_bartoletti",
                        "editor": "Applewood Books",
                        "year": "1971",
                        "genre": "Mythopoeia",
                        "created_at": "2019-03-19T14:59:38.867Z",
                        "updated_at": "2019-03-19T14:59:38.867Z",
                        "rents": []
                    },
                    {
                        "id": 57808,
                        "author": "Mrs. Ruthann Friesen",
                        "title": "A Summer Bird-Cage",
                        "image": "http://smitham.co/tiffaney",
                        "editor": "Harper & Brothers",
                        "year": "1988",
                        "genre": "Humor",
                        "created_at": "2019-03-19T14:59:38.870Z",
                        "updated_at": "2019-03-19T14:59:38.870Z",
                        "rents": []
                    },
                    {
                        "id": 57810,
                        "author": "Alfred Beatty",
                        "title": "The Doors of Perception",
                        "image": "http://dicki.biz/wayne_towne",
                        "editor": "Packt Publishing",
                        "year": "2013",
                        "genre": "Fable",
                        "created_at": "2019-03-19T14:59:38.874Z",
                        "updated_at": "2019-03-19T14:59:38.874Z",
                        "rents": []
                    },
                    {
                        "id": 57811,
                        "author": "Randell Rolfson",
                        "title": "As I Lay Dying",
                        "image": "http://hammes.name/dusti.jerde",
                        "editor": "DAW Books",
                        "year": "2005",
                        "genre": "Fantasy",
                        "created_at": "2019-03-19T14:59:38.876Z",
                        "updated_at": "2019-03-19T14:59:38.876Z",
                        "rents": []
                    },
                    {
                        "id": 57812,
                        "author": "Paris Quitzon",
                        "title": "Clouds of Witness",
                        "image": "http://simonis.biz/dean.harris",
                        "editor": "Bellevue Literary Press",
                        "year": "1931",
                        "genre": "Speech",
                        "created_at": "2019-03-19T14:59:38.879Z",
                        "updated_at": "2019-03-19T14:59:38.879Z",
                        "rents": []
                    },
                    {
                        "id": 57813,
                        "author": "Shaunna Nolan",
                        "title": "Jacob Have I Loved",
                        "image": "http://rath.org/patricia",
                        "editor": "Brimstone Press",
                        "year": "1948",
                        "genre": "Short story",
                        "created_at": "2019-03-19T14:59:38.881Z",
                        "updated_at": "2019-03-19T14:59:38.881Z",
                        "rents": []
                    },
                    {
                        "id": 57815,
                        "author": "Ms. Stephaine Collins",
                        "title": "A Confederacy of Dunces",
                        "image": "http://veumpadberg.org/roy.bahringer",
                        "editor": "Packt Publishing",
                        "year": "1933",
                        "genre": "Science fiction",
                        "created_at": "2019-03-19T14:59:38.886Z",
                        "updated_at": "2019-03-19T14:59:38.886Z",
                        "rents": []
                    },
                    {
                        "id": 57816,
                        "author": "Wilhemina Prosacco DVM",
                        "title": "In a Glass Darkly",
                        "image": "http://tremblay.io/rod",
                        "editor": "Belknap Press",
                        "year": "1938",
                        "genre": "Narrative nonfiction",
                        "created_at": "2019-03-19T14:59:38.888Z",
                        "updated_at": "2019-03-19T14:59:38.888Z",
                        "rents": []
                    },
                    {
                        "id": 57817,
                        "author": "Jacques Daugherty II",
                        "title": "Tirra Lirra by the River",
                        "image": "http://koepp.name/tracey_hilpert",
                        "editor": "Ladybird Books",
                        "year": "1969",
                        "genre": "Textbook",
                        "created_at": "2019-03-19T14:59:38.890Z",
                        "updated_at": "2019-03-19T14:59:38.890Z",
                        "rents": []
                    },
                    {
                        "id": 57818,
                        "author": "Ms. Emil Rolfson",
                        "title": "Nectar in a Sieve",
                        "image": "http://conroy.co/jimmie.kuphal",
                        "editor": "Harvard University Press",
                        "year": "1988",
                        "genre": "Fanfiction",
                        "created_at": "2019-03-19T14:59:38.892Z",
                        "updated_at": "2019-03-19T14:59:38.892Z",
                        "rents": []
                    },
                    {
                        "id": 57820,
                        "author": "Felica Harvey",
                        "title": "In Dubious Battle",
                        "image": "http://smitham.biz/carlton",
                        "editor": "T & T Clark",
                        "year": "2007",
                        "genre": "Classic",
                        "created_at": "2019-03-19T14:59:38.897Z",
                        "updated_at": "2019-03-19T14:59:38.897Z",
                        "rents": []
                    },
                    {
                        "id": 57821,
                        "author": "Mr. Barb McLaughlin",
                        "title": "Such, Such Were the Joys",
                        "image": "http://damore.net/osvaldo",
                        "editor": "Carcanet Press",
                        "year": "1945",
                        "genre": "Textbook",
                        "created_at": "2019-03-19T14:59:38.900Z",
                        "updated_at": "2019-03-19T14:59:38.900Z",
                        "rents": []
                    },
                    {
                        "id": 57824,
                        "author": "Lorenzo Moore",
                        "title": "The Stars' Tennis Balls",
                        "image": "http://osinski.io/zackary.johnston",
                        "editor": "Gefen Publishing House",
                        "year": "1973",
                        "genre": "Textbook",
                        "created_at": "2019-03-19T14:59:38.907Z",
                        "updated_at": "2019-03-19T14:59:38.907Z",
                        "rents": []
                    },
                    {
                        "id": 57825,
                        "author": "Elizabeth Jenkins",
                        "title": "Postern of Fate",
                        "image": "http://ruecker.net/claudio",
                        "editor": "Chick Publications",
                        "year": "1990",
                        "genre": "Comic/Graphic Novel",
                        "created_at": "2019-03-19T14:59:38.909Z",
                        "updated_at": "2019-03-19T14:59:38.909Z",
                        "rents": []
                    }
                ],
                "count": 25,
                "total_pages": 2000,
                "total_count": 50000,
                "current_page": 1,
                "next_page": 2
            }

## Book Member [/api/v1/books/:id]

### Show [GET]

Responds with the information of one unique Book by it's id.

+ Request (application/json)

    + Headers

            access-token: DyVgA1zQCrq38--fWQ8mLg
            client: gNF8jGwgA4-uIfqGoxGo2Q
            uid: test@wolox.com.ar

+ Response 200 (application/json)

            
    + Body

            {
                "id": 57794,
                "author": "Rufus Bartoletti",
                "title": "Dying of the Light",
                "image": "http://bartolettihyatt.io/kasi",
                "editor": "Flame Tree Publishing",
                "year": "1962",
                "genre": "Short story",
                "created_at": "2019-03-19T14:59:38.835Z",
                "updated_at": "2019-03-19T14:59:38.835Z",
                "rents": []
            }

## Rents [/api/v1/rents]

### Index [GET]

Lists all the rents associated to the current logged user (current user session), note that the response is paginated and each page has 25 records.
Pagination is done through [wor-paginate](https://github.com/Wolox/wor-paginate)

+ Request (application/json)

    + Headers

            access-token: DyVgA1zQCrq38--fWQ8mLg
            client: gNF8jGwgA4-uIfqGoxGo2Q
            uid: test@wolox.com.ar

+ Response 200 (application/json)

            
    + Body

            {
                "page": [
                    {
                        "id": 1,
                        "init_date": "0001-01-01",
                        "return_date": "0003-03-03",
                        "book": {
                            "id": 57794,
                            "genre": "Short story",
                            "author": "Rufus Bartoletti",
                            "image": "http://bartolettihyatt.io/kasi",
                            "title": "Dying of the Light",
                            "editor": "Flame Tree Publishing",
                            "year": "1962",
                            "created_at": "2019-03-19T14:59:38.835Z",
                            "updated_at": "2019-03-19T14:59:38.835Z"
                        },
                        "user": {
                            "id": 1,
                            "provider": "email",
                            "uid": "test@wolox.com.ar",
                            "allow_password_change": false,
                            "first_name": "Test",
                            "last_name": "TestLastName",
                            "email": "test@wolox.com.ar",
                            "created_at": "2019-03-19T14:35:39.768Z",
                            "updated_at": "2019-03-27T17:23:56.180Z",
                            "locale": "en"
                        }
                    },
                    {
                        "id": 2,
                        "init_date": "0001-01-01",
                        "return_date": "0003-03-03",
                        "book": {
                            "id": 57795,
                            "genre": "Historical fiction",
                            "author": "Randee Bode",
                            "image": "http://roob.biz/fletcher_parisian",
                            "title": "The Moving Toyshop",
                            "editor": "Borgo Press",
                            "year": "1945",
                            "created_at": "2019-03-19T14:59:38.841Z",
                            "updated_at": "2019-03-19T14:59:38.841Z"
                        },
                        "user": {
                            "id": 1,
                            "provider": "email",
                            "uid": "test@wolox.com.ar",
                            "allow_password_change": false,
                            "first_name": "Test",
                            "last_name": "TestLastName",
                            "email": "test@wolox.com.ar",
                            "created_at": "2019-03-19T14:35:39.768Z",
                            "updated_at": "2019-03-27T17:23:56.180Z",
                            "locale": "en"
                        }
                    },
                    {
                        "id": 3,
                        "init_date": "0001-01-01",
                        "return_date": "0003-03-03",
                        "book": {
                            "id": 57796,
                            "genre": "Fiction narrative",
                            "author": "Dr. Samual Hayes",
                            "image": "http://borer.name/cyndi.kunde",
                            "title": "An Instant In The Wind",
                            "editor": "Mark Batty Publisher",
                            "year": "1991",
                            "created_at": "2019-03-19T14:59:38.843Z",
                            "updated_at": "2019-03-19T14:59:38.843Z"
                        },
                        "user": {
                            "id": 1,
                            "provider": "email",
                            "uid": "test@wolox.com.ar",
                            "allow_password_change": false,
                            "first_name": "Test",
                            "last_name": "TestLastName",
                            "email": "test@wolox.com.ar",
                            "created_at": "2019-03-19T14:35:39.768Z",
                            "updated_at": "2019-03-27T17:23:56.180Z",
                            "locale": "en"
                        }
                    },
                    {
                        "id": 4,
                        "init_date": "0001-01-01",
                        "return_date": "0003-03-03",
                        "book": {
                            "id": 57797,
                            "genre": "Short story",
                            "author": "Jared O'Reilly",
                            "image": "http://green.info/harlan.feeney",
                            "title": "The Green Bay Tree",
                            "editor": "Open Court Publishing Company",
                            "year": "2003",
                            "created_at": "2019-03-19T14:59:38.845Z",
                            "updated_at": "2019-03-19T14:59:38.845Z"
                        },
                        "user": {
                            "id": 1,
                            "provider": "email",
                            "uid": "test@wolox.com.ar",
                            "allow_password_change": false,
                            "first_name": "Test",
                            "last_name": "TestLastName",
                            "email": "test@wolox.com.ar",
                            "created_at": "2019-03-19T14:35:39.768Z",
                            "updated_at": "2019-03-27T17:23:56.180Z",
                            "locale": "en"
                        }
                    },
                    {
                        "id": 5,
                        "init_date": "0001-01-01",
                        "return_date": "0003-03-03",
                        "book": {
                            "id": 57798,
                            "genre": "Fiction narrative",
                            "author": "Daren Harvey",
                            "image": "http://connellyko.com/rosaria",
                            "title": "Nine Coaches Waiting",
                            "editor": "Manchester University Press",
                            "year": "1998",
                            "created_at": "2019-03-19T14:59:38.847Z",
                            "updated_at": "2019-03-19T14:59:38.847Z"
                        },
                        "user": {
                            "id": 1,
                            "provider": "email",
                            "uid": "test@wolox.com.ar",
                            "allow_password_change": false,
                            "first_name": "Test",
                            "last_name": "TestLastName",
                            "email": "test@wolox.com.ar",
                            "created_at": "2019-03-19T14:35:39.768Z",
                            "updated_at": "2019-03-27T17:23:56.180Z",
                            "locale": "en"
                        }
                    }
                ],
                "count": 5,
                "total_pages": 1,
                "total_count": 5,
                "current_page": 1,
                "next_page": null
            }

### Create [POST]
Creates a rent associated to the user and book sent in the http request.
Users can only create a Rent for themselves.

+ Request (application/json)
    
    + Body
    
            {
                "rent": {
                    "user_id": 1,
                    "book_id": 57794,
                    "init_date": "01/01/01",
                    "return_date": "02/02/02"
                }
            }
    
    + Headers

            access-token: DyVgA1zQCrq38--fWQ8mLg
            client: gNF8jGwgA4-uIfqGoxGo2Q
            uid: test@wolox.com.ar
            

+ Response 201 (application/json)
            
    + Body

            {
                "id": 7,
                "init_date": "0001-01-01",
                "return_date": "0002-02-02",
                "book": {
                    "id": 57794,
                    "genre": "Short story",
                    "author": "Rufus Bartoletti",
                    "image": "http://bartolettihyatt.io/kasi",
                    "title": "Dying of the Light",
                    "editor": "Flame Tree Publishing",
                    "year": "1962",
                    "created_at": "2019-03-19T14:59:38.835Z",
                    "updated_at": "2019-03-19T14:59:38.835Z"
                },
                "user": {
                    "id": 1,
                    "provider": "email",
                    "uid": "test@wolox.com.ar",
                    "allow_password_change": false,
                    "first_name": "Test",
                    "last_name": "TestLastName",
                    "email": "test@wolox.com.ar",
                    "created_at": "2019-03-19T14:35:39.768Z",
                    "updated_at": "2019-03-27T18:30:08.216Z",
                    "locale": "en"
                }
            }
            
            
## Book Suggestions [/api/v1/book_suggestions]

### Create [POST]
Creates a book suggestion, note that authentification headers are not necessary in the request, so an unauthenticated person can create suggestions.

+ Request (application/json)
    
    + Body
    
            { 
                "book_suggestion": { 
                    "author": "some author", 
                    "synopsis": "some synopsis", 
                    "link": "some link", 
                    "price": 123123, 
                    "title": "some title", 
                    "editor": "some editor", 
                    "year": "1997", 
                    "user_id": 2 
                } 
            }
    

+ Response 201 (application/json)
            
    + Body
        
            {
                "id": 11,
                "synopsis": "some synopsis",
                "price": 123123,
                "author": "some author",
                "title": "some title",
                "link": "some link",
                "editor": "some editor",
                "year": "1997",
                "user_id": 2,
                "created_at": "2019-03-27T19:15:19.339Z",
                "updated_at": "2019-03-27T19:15:19.339Z"
            }

            
## Open Library Search [/api/v1/open_library_requests/search]

### Search [GET]
Imports a book from [Open Library](https://openlibrary.org/) by it's [ISBN](https://en.wikipedia.org/wiki/International_Standard_Book_Number).

+ Request (application/json)
    
    + Body
    
            {
                "isbn": 100
            }
            
            
    + Headers

            access-token: DyVgA1zQCrq38--fWQ8mLg
            client: gNF8jGwgA4-uIfqGoxGo2Q
            uid: test@wolox.com.ar
    

+ Response 200 (application/json)
            
    + Body
        
            { 
                "isbn": 100, 
                "title": "Notes on financial rules.", 
                "subtitle": "Secretariat Training School",
                "number_of_pages": 562, 
                "authors": 
                    [ 
                        { 
                            "url": "https://openlibrary.org/authors/OL2552A/Secretariat_Training_School_(India)", 
                            "name": "Secretariat Training School (India)" 
                        } 
                    ] 
            }

